import type { Metadata, Viewport } from "next";
import { IBM_Plex_Mono, Instrument_Sans } from "next/font/google";
import { INTRO_GATE_SCRIPT, INTRO_GATE_STYLE } from "@/components/home/IntroGate";
import "./globals.css";

// Upright only. specs/00-foundation.md asks for the italic too, but nothing on the home page
// sets it and next/font preloads every declared face, so it cost a high-priority 32KB download
// ahead of the upright file the hero needs. A later page that sets italic should add
// `style: ["normal", "italic"]` back here.
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

// The capability panels set their ledgers and counters in IBM Plex Mono. The prototype names
// it without loading it, so it only rendered where the font happened to be installed.
// Not preloaded: that text sits screens below the fold and phones never render it. The stage
// lays it out at mount on desktop, which still fetches the file during load, and the size-
// adjusted fallback keeps the swap from moving anything.
const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
  preload: false,
});

const title = "3264.ai — AI software deployment";
const description =
  "3264 builds and runs AI systems inside banking, fund management and asset management firms. Scope is fixed before we start. You are billed for what reaches production.";

// Share and search metadata. NEXT_PUBLIC_SITE_URL points the absolute URLs (canonical,
// og:url, og:image) at another origin, e.g. a staging domain; production is 3264.ai. "./"
// resolves against each page's own path, so pages added later canonicalise to themselves
// rather than inheriting the home page's URL. The share image, its alt text and the icons are
// file conventions in this folder (generated by scripts/brand-assets.mjs); Next adds their
// tags and reuses the share image for the Twitter card.
export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "https://3264.ai"),
  title,
  description,
  alternates: { canonical: "./" },
  openGraph: { type: "website", siteName: "3264.ai", title, description, url: "./", locale: "en_US" },
  twitter: { card: "summary_large_image" },
};

export const viewport: Viewport = {
  themeColor: "#F6F5F2",
};

// `?motion=off` freezes every motion system for deterministic screenshots. It runs before
// first paint so the flag is on <html> by the time any effect reads it.
const MOTION_FLAG = `try{if(/[?&]motion=off(&|$)/.test(location.search))document.documentElement.setAttribute("data-motion","off")}catch(e){}`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${plexMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: MOTION_FLAG }} />
        {/* The home intro decides before first paint whether it will play, so the first frame
            is its page-colour cover rather than the page it is about to cover (IntroGate.ts). */}
        <script dangerouslySetInnerHTML={{ __html: INTRO_GATE_SCRIPT }} />
        <style dangerouslySetInnerHTML={{ __html: INTRO_GATE_STYLE }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
