import type { Metadata, Viewport } from "next";
import { INTRO_GATE_SCRIPT, INTRO_GATE_STYLE } from "@/components/home/IntroGate";
import { PC_INTRO_GATE_SCRIPT } from "@/components/private-credit/IntroGate";
import "./globals.css";

// Fonts are self-hosted under their literal family names (see globals.css): the Private
// Credit motion module names them in inline styles and canvas fonts. The two upright faces
// every page sets above the fold are preloaded; the rest load on use.
const PRELOAD_FONTS = [
  "/fonts/instrument-sans-latin-400-normal.woff2",
  "/fonts/instrument-sans-latin-500-normal.woff2",
];

const title = "3264.ai — AI software deployment";
const description =
  "3264 builds and runs AI systems inside banking, fund management and asset management firms. Scope is fixed before we start. You are billed for what reaches production.";

// Share and search metadata. NEXT_PUBLIC_SITE_URL points the absolute URLs (canonical,
// og:url, og:image) at another origin, e.g. a staging domain; production is 3264.ai. "./"
// resolves against each page's own path, so pages added later canonicalise to themselves
// rather than inheriting the home page's URL. The share image, its alt text and the icons are
// file conventions in this folder (generated by scripts/brand-assets.mjs); Next adds their
// tags and reuses the share image for the Twitter card.
export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "https://3264.ai"),
  title,
  description,
  alternates: { canonical: "./" },
  openGraph: { type: "website", siteName: "3264.ai", title, description, url: "./", locale: "en_US" },
  twitter: { card: "summary_large_image" },
};

export const viewport: Viewport = {
  themeColor: "#F6F5F2",
};

// `?motion=off` freezes every motion system for deterministic screenshots. It runs before
// first paint so the flag is on <html> by the time any effect reads it.
const MOTION_FLAG = `try{if(/[?&]motion=off(&|$)/.test(location.search))document.documentElement.setAttribute("data-motion","off")}catch(e){}`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {PRELOAD_FONTS.map((href) => (
          <link key={href} rel="preload" href={href} as="font" type="font/woff2" crossOrigin="anonymous" />
        ))}
        <script dangerouslySetInnerHTML={{ __html: MOTION_FLAG }} />
        {/* The home intro decides before first paint whether it will play, so the first frame
            is its page-colour cover rather than the page it is about to cover (IntroGate.ts). */}
        <script dangerouslySetInnerHTML={{ __html: INTRO_GATE_SCRIPT }} />
        <style dangerouslySetInnerHTML={{ __html: INTRO_GATE_STYLE }} />
        {/* Same for the Private Credit intro, on that route only (IntroGate.ts there). */}
        <script dangerouslySetInnerHTML={{ __html: PC_INTRO_GATE_SCRIPT }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
