import type { Metadata } from "next";

/**
 * The site share image: opengraph-image.png in this folder (generated by
 * scripts/brand-assets.mjs) at the path the file convention serves it from, with the alt text of
 * opengraph-image.alt.txt beside it; metadataBase makes the URL absolute.
 */
const SHARE_IMAGE = { url: "/opengraph-image.png", width: 1200, height: 630, alt: "3264.ai — Deployment is the deliverable." };

/**
 * A page's title, description and share card. Setting `openGraph` on a page replaces the root
 * layout's, and with it the share image the root's opengraph-image.png supplies, so every page
 * that sets one names the image again: build page metadata here and it does. `openGraph` adds to
 * or overrides the card, e.g. an article's type and dates. The X card follows og:image (the root
 * layout sets `twitter.card` and no page sets `twitter`).
 */
export function pageMetadata({
  title,
  description,
  openGraph,
}: {
  title: string;
  description: string;
  openGraph?: NonNullable<Metadata["openGraph"]>;
}): Metadata {
  return {
    title,
    description,
    openGraph: {
      type: "website",
      siteName: "3264.ai",
      locale: "en_US",
      title,
      description,
      url: "./",
      images: [SHARE_IMAGE],
      ...openGraph,
    },
  };
}
